### ISSUE TITLE
cannot run  set origin.py script

### ISSUE THREAD

**Issue by octobotics** [thien94/vision_to_mavros#47]
I am getting this strange error , even though yaml is installed for python 2.7

Traceback (most recent call last):
  File "/home/octo/catkin_ws/src/vision_to_mavros/scripts/set_origin.py", line 9, in <module>
    import rospy
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/__init__.py", line 47, in <module>
    from std_msgs.msg import Header
  File "/opt/ros/melodic/lib/python2.7/dist-packages/std_msgs/msg/__init__.py", line 1, in <module>
    from ._Bool import *
  File "/opt/ros/melodic/lib/python2.7/dist-packages/std_msgs/msg/_Bool.py", line 6, in <module>
    import genpy
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genpy/__init__.py", line 34, in <module>
    from . message import Message, SerializationError, DeserializationError, MessageException, struct_I
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genpy/message.py", line 48, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

**Comment by thien94** [comment]
You could try:
- verify which python version is the default one. If possible, install `yaml` in python3 as well,
- run the script in python2 and python3 and see which is the correct version.
